name: ci

on:
  push:
   branches:
    - feature/workflows
    - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.21'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/open-feature/go-sdk-contrib
      GOBIN: /home/runner/work/open-feature/go-sdk-contrib/bin
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Module cache
        uses: actions/cache@v4
        env:
          cache-name: go-mod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      - name: Run workspace init
        run: make workspace-init
      - name: Run linter
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Module cache
        uses: actions/cache@v4
        env:
          cache-name: go-mod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      - name: Run workspace init
        run: make workspace-init
      - name: Run tests, including e2e
        run: make e2e
